name: deploy-ec2-aws

on:
  workflow_dispatch:

env:
  NODE_VERSION: 14

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy ec2
        uses: appleboy/ssh-action@master
        with:
          host: ec2-18-118-22-233.us-east-2.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          script: |
            ls -la
