name: deploy-ec2-aws

on:
  workflow_dispatch:

env:
  NODE_VERSION: 14

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy ec2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            pm2 kill p2p-backend-api
            echo "App killed"
            cd /home/ec2-user/pes-apps
            rm -rf p2p-backend-api
            git clone 
            cd p2p-backend-api
            npm install
            npm run build
            pm2 kill
            pm2 start --daemon ./dist/main.js --name p2p-backend-api
