name: deploy-ec2-aws

on:
  workflow_dispatch:

env:
  NODE_VERSION: 14

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy ec2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ec2-user/pes-apps
            git fetch
            git reset --hard origin/master
            git pull
            npm install
            npm run build
            pm2 kill
            pm2 start --daemon ./dist/main.js --name p2p-backend-api
