name: deploy-ec2-aws

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: 14

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy ec2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            pm2 stop p2p-backend-api
            echo "App killed"
            cd /home/ec2-user/pes-apps
            rm -rf p2p-backend-api
            git clone 
            cd p2p-backend-api
            git checkout feature/rework-in-nestjs
            npm install
            npm run build
            pm2 start npm --name "p2p-backend-api" -- start
