name: deploy-ec2-aws

on:
  workflow_dispatch:

env:
  NODE_VERSION: 14

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build
        run: |
          npm install
          npm run build

      - name: Deploy ec2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /home/ec2-user/pes-apps
            git fetch
            git reset --hard origin/master
            git pull
            npm install
            npm run build
            pm2 kill
            pm2 start --daemon ./dist/main.js --name p2p-backend-api
